name: vscode_snippet_to_sublime_snippet
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/james2doyle/vscode-snippet-to-sublime-snippet

environment:
  sdk: '>=3.0.0-122.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  args: ^2.3.1
  characters: ^1.2.1
  slugify_string: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
