name: Build on Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [dev]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze
      - name: Run tests
        run: dart test
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sdk: [dev]
        include:
          - os: ubuntu-latest
            output-name: converter-ubuntu-latest
          - os: macos-latest
            output-name: converter-macos-latest
          - os: windows-latest
            output-name: converter-windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Build binaries
        run: dart compile exe bin/vscode_snippet_to_sublime_snippet.dart -o converter-${{ matrix.os }}
      - name: Archive compiled packages
        uses: actions/upload-artifact@v3
        with:
          name: converter-${{ matrix.os }}
          path: converter-${{ matrix.os }}
